FROM alpine:latest

# Set environment variables
ENV MIX_ENV=prod

# Copy tarball release
ADD _build/prod/lofter-0.1.0.tar.gz ./

RUN apk add --no-cache bash openssl libgcc libstdc++ ncurses-libs

# Set user
USER nobody:nobody

# Set entrypoint
ENTRYPOINT ["./bin/lofter"]
